services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: "portainer"
    #Usuário admin
    #Senha: testeadmin1234
    ports:
      - 8000:8000
      - 9443:9443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
  postgres-vendinha:
    image: postgres:12.4
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: vendinha
    ports:
      - "5432:5432"
  app:
    build: .
    ports:
      - 5217:5217
    depends_on:
      - "db"
  
